### ISSUE TITLE
Hamcrest matchers for ServiceException / RemoteException

### ISSUE THREAD

**Issue by meditativeape** [palantir/http-remoting-api#35]
Something nice to have: aside from the assert classes provided in test-utils, could we add equivalent Hamcrest matchers that works with JUnit's ExpectedException? I imagine it will look like this:
```
private Matcher<ServiceException> getServiceExceptionMatcher(ErrorType errorTypeToMatch) {
        return new BaseMatcher<ServiceException>() {
            @Override
            public boolean matches(Object item) {
                if (!(item instanceof ServiceException)) {
                    return false;
                }
                ServiceException castedItem = (ServiceException) item;
                return errorTypeToMatch.equals(castedItem.getErrorType());
            }

            @Override
            public void describeMismatch(Object item, Description description) {
                if (item instanceof ServiceException) {
                    description.appendText("was ServiceException with ErrorType ")
                            .appendValue(((ServiceException) item).getErrorType());
                } else {
                    super.describeMismatch(item, description);
                }
            }

            @Override
            public void describeTo(Description description) {
                description.appendText("ServiceException with ErrorType ").appendValue(errorTypeToMatch);
            }
        };
    }
```

**Comment by uschi2000** [comment]
Alternatively, what's blocking you from using assertj?

**Comment by meditativeape** [comment]
There's no blocker, it's just some of our existing tests use `ExpectedException` and it would be nice to not have to refactor them. Also, it's a little bit cleaner to do:
```
expectedException.expect(...);
myTestStatement.run();
```
comparing to
```
try {
    myTestStatement.run();
    fail();
} catch (ServiceException e) {
    Assertions.assert(e)....
}
```

**Comment by markelliot** [comment]
assertj style would be more like:

assertThatThrownBy(() -> myTestStatement.run())
    .hasMessage(…)
…

**Comment by meditativeape** [comment]
Oh I see, thanks for the example Mark. But I can't seem to chain it with [hasType](https://github.com/palantir/http-remoting-api/blob/develop/test-utils/src/main/java/com/palantir/remoting/api/testing/ServiceExceptionAssert.java#L32):
```
import com.palantir.remoting.api.testing.Assertions;

Assertions.assertThatThrownBy(() -> myTestStatement.run())
        .hasType(myErrorType);  // fails, because assertThatThrownBy returns an AbstractThrowableAssert, not ServiceExceptionAssert
```

I imagine `Assertions` class should implement a custom `assertThatServiceExceptionIsThrownBy()` that returns `ServiceExceptionAssert`?

**Comment by uschi2000** [comment]
Yes, I think this could be done, I'm not sure how easy it is though.

**Comment by uschi2000** [comment]
If you want to contribute this, I'd happily take a PR!

**Comment by meditativeape** [comment]
Took a quick look and seem doable. I'll take a stab at it.
