### ISSUE TITLE
New Error Code: CONFLICT(409)

### ISSUE THREAD

**Issue by meditativeape** [palantir/http-remoting-api#43]
Wanted to add a new error code into the list available in `ErrorType`: [Conflict (409)](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10)

Use case is for reporting error when a request wants to open a new transaction when one already exists, as our service does not currently support simultaneous open transactions. I think 409 is the HTTP code that most accurately describes this error.

**Comment by uschi2000** [comment]
Is failed precondition not good enough for this?

Sent from Email+ secured by MobileIron

-------- Original Message --------

**Comment by meditativeape** [comment]
Failed precondition sounds close, but it's a 500, and I think in my case a client error is more appropriate since nothing actually goes wrong on the server side.

**Comment by uschi2000** [comment]
OK, that's fair. I think we can add CONFLICT (409).
