### ISSUE TITLE
Unable to extend PartialServiceConfiguration

### ISSUE THREAD

**Issue by pkoenig10** [palantir/http-remoting-api#72]
It is impossible to extend `PartialServiceConfiguration` to support service discovery in cases where more information is required and is provided by the discovered service (for instance, a `type` field). This is because the Immutables processor prevents extending from value types. Attempting to do so yields the following error message:

```
Should not inherit com.palantir.remoting.api.config.service.PartialServiceConfiguration which is a value type itself.
Avoid extending from another abstract value type.
Better to share common abstract class or interface which are not carrying @Immutable annotation.
```

**Comment by felixdesouza** [comment]
As a work around to having Remoting expose this common interface, you could do something with `@JsonUnwrapped`

e.g. 
```java
@Value.Immutable
@JsonDeserialize(...)
@JsonSerialize(...)
abstract class MySpecialServiceConfiguration implements PartialServiceConfiguration {
   @JsonUnwrapped
   abstract PartialServiceConfiguration partialServiceConfiguration();

   abstract String type();

   // ... extra keys you care about
}
```

**Comment by pkoenig10** [comment]
`@JsonUnwrapped` definitely seems like a more appropriate solution to this issue than remoting exposing a non-annotated interface. I didn't realize that existed. Can close this out.
